### ISSUE TITLE
The resolved config file doesn't contain a resolve configuration

### ISSUE THREAD

**Issue by yormi** [adriantoine/babel-plugin-webpack-alias-examples#1]
Hi there,

I'm trying to upgrade my setup with this lovely plugin but:

`npm install && npm test` outputs this:

```
Error: /home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/webpack.config.js: The resolved config file doesn't contain a resolve configuration
    at PluginPass.CallExpression (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-plugin-webpack-alias/build/index.js:34:27)
    at newFn (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/index.js:161:17)
    at traverse (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/index.js:83:12)
    at File.transform (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-core/lib/transformation/file/index.js:531:35)
    at /home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-core/lib/transformation/file/index.js:547:16)
    at Pipeline.transform (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.transformFileSync (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-core/lib/api/node.js:138:10)
    at compile (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-register/lib/node.js:120:20)
    at loader (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-register/lib/node.js:146:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at configPath (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-plugin-webpack-alias/build/index.js:182:20)
    at arraySome (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/lodash.some/index.js:140:9)
    at some (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/lodash.some/index.js:1838:10)
    at getConfig (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-plugin-webpack-alias/build/index.js:167:26)
    at PluginPass.CallExpression (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-plugin-webpack-alias/build/index.js:25:30)
    at newFn (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/index.js:161:17)
    at traverse (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-traverse/lib/index.js:83:12)
    at File.transform (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-core/lib/transformation/file/index.js:531:35)
    at /home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-core/lib/transformation/file/index.js:547:16)
    at Pipeline.transform (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.transformFileSync (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-core/lib/api/node.js:138:10)
    at compile (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-register/lib/node.js:120:20)
    at loader (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-register/lib/node.js:146:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/mocha/lib/mocha.js:485:10)
    at Object.<anonymous> (/home/guillaume/Desktop/babel-plugin-webpack-alias-examples/mocha/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

It seems that when webpack.config.js has something else (before or after) than just modules.exports = {...} it exports an empty object.

Let me know if I can be of any help. I'm trying to investigate that weird behavior at the moment.

**Comment by adriantoine** [comment]
Thanks for raising the issue, it has been pointed out by @ijpiantanida here https://github.com/trayio/babel-plugin-webpack-alias/issues/8#issuecomment-242960029, I'm having a look

**Comment by adriantoine** [comment]
As @ijpiantanida said, when you remove the `path` reference in the webpack file like that:

```
module.exports = {
    resolve: {
        alias: {
            'alias': './deep/folder/alias',
        }
    }
};
```

then it works. So I thought there was something wrong with importing `path`. But when you revert the webpack file back to the original one (with the `var path = require('path');`) it still works and there's no way to break it again 🤔

**Comment by adriantoine** [comment]
Running the mocha test with the env variable `BABEL_DISABLE_CACHE` set to `1` allows to reproduce the issue all the time.

``` bash
BABEL_DISABLE_CACHE=1 mocha --compilers js:babel-register
```

**Comment by adriantoine** [comment]
Reverting to `babel-plugin-webpack-alias@1.6.0` fixes the issue, so it is a regression.

**Comment by yormi** [comment]
I'm surprised google failed me on that one :P

Yes it's exactly the same problem. I didn't know about `BABEL_DISABLE_CACHE`. Thanks.

I'll keep looking a bit otherwise I'll just use `1.6.0`

**Comment by adriantoine** [comment]
Ok so the issue is in the `1.8.3` release, even reverting to `1.8.2` works.

Sorry for that! I'll publish a `1.8.4` that looks exactly like `1.8.2` to avoid issues for people installing the latest.

Also I will close that and add an issue on the `babel-plugin-webpack-alias` repo!

Once again, sorry for the inconvenience!

**Comment by yormi** [comment]
Wow ! That's what I call quick and great help ! Thanks a lot @adriantoine :)

**Comment by ijpiantanida** [comment]
@adriantoine thanks looking into it so quickly!!!! You're awesome haha
